app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('app1first/',app1first,name='app1first'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('app2first/',app2first,name='app2first'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app3first/',app3first,name='app3first')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def app1first(request):
    return render(request,'app1first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2first(request):
    return render(request,'app2first.html')

app3/views.py
from django.shortcuts import render

# Create your views here.

def app3first(request):
    return render(request,'app3first.html')

templates/app1first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is my app1</h1>
        <h1>this is app1 html page</h1>
        <a href="{% url 'app2:app2first' %}"><h1>click here to go to app2</h1></a>
    </center>
</body>
</html>

templates/app2first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is my app2</h1>
        <h1>this is app2 html page</h1>
        <a href="{% url 'app3first' %}"><h1>click here to go to app3</h1></a>
    </center>
</body>
</html>

templates/app3first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is my app3</h1>
        <h1>this is app3 html page</h1>
        <a href="{% url 'app1:app1first' %}"><h1>back to first app1</h1></a>
    </center>
</body>
</html>